# SITE CONFIGURATION
baseurl: "/blog"
url: ""

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Three Steps Forward
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: d811beaa78cebee0955ff8521753f467
  description: "Andy Duss's personal writings, thoughts, and feelings"

  # Header and footer text
  header_text: >
     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

     <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  header_text_feature_image:
  footer_text: >
   Powered by Coffee and <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>, a theme for <a href="https://jekyllrb.com/">Jekyll</a>

  # Icons
  rss: false
  email_address: mindovermiles262@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "mindovermiles262"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit: "mindovermiles262"
  soundcloud:
  stack_exchange: https://stackoverflow.com/users/7721999/andy
  steam:
  tumblr:
  twitter: "mindovermiles26"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
